"""Added file column in image table

Revision ID: 4fc555326eb8
Revises: bd1f82a4453b
Create Date: 2019-04-08 15:57:47.511278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc555326eb8'
down_revision = 'bd1f82a4453b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('file')

    # ### end Alembic commands ###
