"""Added file column in image table

Revision ID: bd1f82a4453b
Revises: e67efd243037
Create Date: 2019-04-07 17:34:56.145156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1f82a4453b'
down_revision = 'e67efd243037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('file')

    with op.batch_alter_table('text', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('text_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_file', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('file')

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', sa.BLOB(), nullable=True))
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
